#:schema node_modules/wrangler/config-schema.json
name = "aimpact"
compatibility_flags = ["nodejs_compat"]
compatibility_date = "2025-03-28"
pages_build_output_dir = "./build/client"
send_metrics = false

[vars]
PUBLIC_BACKEND_URL = "https://t7s6acu4sta5774h5kboadp7ms.ingress.d3akash.cloud"
VITE_DEPOSIT_ADDRESS = "GorN1wMsaWp75QJYtU8NrCu9GCgTtPiUeDRX3ccLZ5jj"
